apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: kalyanramm237/bookapp:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_ROOT_USERNAME
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 256Mi
