apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
      - name: bookapp
        image: kalyanramm237/bookapp:latest
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
