services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  bookapp:
    build: ./bookapp
    ports:
      - 8080:8080
    depends_on:
      - db

  studentapp:
    build: ./studentapp
    ports:
      - 8081:8081
    depends_on:
      - db

  booklendingapp:
    build: ./BookLendingApp
    ports:
      - 5001:5001
    depends_on:
      - db
      - bookapp
      - studentapp
  