---
- name: Pull Docker Image of Library App
  hosts: all

   vars:
    ansible_python_interpreter: /Users/vikaskaly/base/bin/python
  
  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Install Docker Compose (if not installed)
      shell: |
        if ! command -v docker-compose &> /dev/null; then
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
        fi
      args:
        executable: /bin/bash

    - name: Copy docker-compose.yml to target machine
      copy:
        src: "{{ workspace }}/docker-compose.yml"  # Use Jenkins workspace or specify path
        dest: "/home/{{ ansible_ssh_user }}/docker-compose.yml"  # Use ansible_ssh_user

    - name: Pull Docker images
      shell: docker compose -f /home/{{ ansible_ssh_user }}/docker-compose.yml pull
      args:
        chdir: "/home/{{ ansible_ssh_user }}"

    - name: Run Docker containers
      shell: docker compose -p libraryapp -f /home/{{ ansible_ssh_user }}/docker-compose.yml up -d
      args:
        chdir: "/home/{{ ansible_ssh_user }}"
