---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Install Docker Compose (if not installed)
      shell: |
        if ! command -v docker-compose &> /dev/null; then
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
        fi
      args:
        executable: /bin/bash

    - name: Pull Image
      shell: docker-compose -p libraryapp pull

    - name: Run the container
      shell: docker-compose -p libraryapp up