---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Install Docker Compose (if not installed)
      shell: |
        if ! command -v docker-compose &> /dev/null; then
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
        fi
      args:
        executable: /bin/bash

    # - name: Pull Image
    #   shell: docker-compose pull

    # - name: Run the container
    #   shell: docker-compose -p libraryapp up
    - name: Copy docker-compose.yml to target machine
      copy:
        src: "{{ workspace }}/docker-compose.yml"
        dest: /opt/libraryapp/docker-compose.yml

    - name: Pull Docker images
      shell: docker-compose -f /opt/libraryapp/docker-compose.yml pull
      args:
        chdir: /opt/libraryapp

    - name: Run Docker containers
      shell: docker-compose -p libraryapp -f /opt/libraryapp/docker-compose.yml up -d
      args:
        chdir: /opt/libraryapp