---
- name: Pull Docker Image of Library App
  hosts: all
  
  tasks:
    - name: Copy docker-compose.yml to target machine
      copy:
        src: "{{ workspace }}/docker-compose.yml"  # Use Jenkins workspace or specify path
        dest: "/Users/{{ ansible_ssh_user }}/docker-compose.yml"  # Use ansible_ssh_user

    - name: Pull Docker images
      shell: docker compose -f /Users/{{ ansible_ssh_user }}/docker-compose.yml pull
      args:
        chdir: "/Users/{{ ansible_ssh_user }}"

    - name: Run Docker containers
      shell: docker compose -p libraryapp -f /Users/{{ ansible_ssh_user }}/docker-compose.yml up -d
      args:
        chdir: "/Users/{{ ansible_ssh_user }}"
