services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3305:3306
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

  bookapp:
    build: ./Library-Backend/bookapp
    ports:
      - 8082:8082
    depends_on:
      - db

  studentapp:
    build: ./Library-Backend/studentapp
    ports:
      - 8081:8081
    depends_on:
      - db

  booklendingapp:
    build: ./Library-Backend/BookLendingApp
    ports:
      - 5001:5001
    depends_on:
      - db
      - bookapp
      - studentapp

  frontend:
    build: ./Library-Frontend
    ports:
      - 5173:5173
    depends_on:
      - booklendingapp

volumes:
  mysql-data:
    driver: local