services:
  # MySQL database service
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3305:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  # Book application backend service
  bookapp:
    build: ./Library-Backend/bookapp
    image: vikaskaly/bookapp:latest
    ports:
      - 8082:8082
    depends_on:
      - db

  # Student application backend service
  studentapp:
    build: ./Library-Backend/studentapp
    image: vikaskaly/studentapp:latest
    ports:
      - 8081:8081
    depends_on:
      - db

  # Book lending application service
  booklendingapp:
    build: ./Library-Backend/BookLendingApp
    image: vikaskaly/booklendingapp:latest
    ports:
      - 5001:5001
    depends_on:
      - db
      - bookapp
      - studentapp

  # Frontend application service
  frontend:
    build: ./Library-Frontend
    image: vikaskaly/frontend:latest
    ports:
      - 5173:5173
    depends_on:
      - booklendingapp

volumes:
  mysql-data:
    driver: local
