apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bookapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookapp
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: studentapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studentapp
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booklendingapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booklendingapp
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: library-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: library-frontend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50