apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
      - name: library-frontend
        image: kalyanramm237/frontend:latest
        ports:
        - containerPort: 5173
        resources:
          limits:
            cpu: 800m
            memory: 800Mi
          requests:
            cpu: 700m
            memory: 500Mi
