apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklendingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booklendingapp
  template:
    metadata:
      labels:
        app: booklendingapp
    spec:
      containers:
      - name: booklendingapp
        image: kalyanramm237/booklendingapp:latest
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
