apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - name: studentapp
        image: kalyanramm237/studentapp:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-app-secrets
              key: MYSQL_ROOT_USERNAME
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
