apiVersion: v1
kind: Service
metadata:
  name: library-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: library-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
