- name: Check Minikube Status
  shell: minikube status | grep -i "running"
  register: minikube_status
  ignore_errors: true  # Ignore errors if Minikube isn't running
  
- name: Start minikube
  shell: minikube start --driver=docker
  when: minikube_status.rc != 0
